config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create]
  resources :users, only: :show do
    resource :profile, only: [:edit, :update] do
      patch :avatar
    end
  end
  get :geo, to: 'profiles#geo'
  resources :notifications, only: [:index, :show, :create]

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show]
  end

  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: /.+@.+\..+/i }
  validates :password, length: { in: 6..30 }

  has_many :sent_notifications, class_name: Notification, foreign_key: :sender_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :content, presence: true

  belongs_to :receiver, class_name: User
  belongs_to :sender, class_name: Admin

  after_commit :send_notification

  private

  def send_notification
    NotificationJob.perform_later(self)
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  attr_accessor :avatar, :lat, :lng

  belongs_to :user

  validates :avatar, file_content_type: { allow: %r{^image\/.*} }

  after_validation :upload_avatar

  def full_name
    "#{first_name} #{last_name}".strip
  end

  private

  def upload_avatar
    self.avatar_id = FlickrService.upload(user, avatar) if avatar && !avatar_id
  end
end

app/models/session.rb
class Session < VirtualModel
  attr_accessor :email, :password

  delegate :id, to: :user, prefix: true

  validates :email, :password, presence: true
  validate :credentials, unless: -> { password.blank? }

  def user
    @user ||= User.find_by_email(email.downcase)
  end

  private

  def credentials
    errors.add(:email, :invalid) && return if user.nil?
    errors.add(:password, :pending) if user.password_digest.nil?
    errors.add(:email, :invalid) unless user.authenticate(password)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: /.+@.+\..+/i }
  validates :password, length: { in: 6..30 }
  validates :password_confirmation, presence: true

  has_one :profile, dependent: :destroy
  has_many :received_notifications, class_name: Notification, foreign_key: :receiver_id
  has_and_belongs_to_many :companies

  after_create :create_profile

  delegate :full_name, to: :profile
  delegate :location, to: :profile
end

app/models/virtual_model.rb
class VirtualModel
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def initialize(attrs = {})
    attrs ||= {}
    attrs.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < AdminController
  def create
    if admin.try(:authenticate, params[:password])
      session[:admin_id] = admin.id
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to new_admin_session_path
  end

  private

  def admin
    @admin ||= Admin.find_by(email: params[:email])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :require_admin

  def index
    params[:page] ||= 1
    @users = User.all.page(params[:page])
  end

  def show
    @profile = user.profile
    @notification = user.received_notifications.build
  end

  private

  def user
    @user ||= User.joins(:profile).find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  rescue ActiveRecord::RecordNotFound
    reset_session
  end
  helper_method :current_admin

  def require_admin
    redirect_to new_admin_session_path unless current_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    reset_session
  end
  helper_method :current_user

  def require_user
    redirect_to new_session_path unless current_user
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end

  def create
    @notification = Notification.new(notification_params)
    @notification.valid? && @notification.save
  end

  private

  def notification_params
    params.require(:notification).permit(:receiver_id, :sender_id, :content)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user
  before_action :profile, except: :geo

  def update
    @profile.update(profile_params)
    redirect_to current_user
  end

  def avatar
    @profile.avatar = params[:avatar]
    flash[:avatar] = 'Wrong avatar upload' unless profile.valid? && profile.save
    redirect_to :back
  end

  def geo
    @locations = LocationService.geo(params[:address])
    respond_to do |format|
      format.js { render 'geo'}
    end
  end

  private

  def profile_params
    params.require(:profile).permit!
  end

  def profile
    @profile ||= current_user.profile
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.save
      confirm_user
      redirect_to new_session_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def confirm_user
    UserMailer.confirm_registration(@user).deliver_now
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params[:session])
    if @session.valid?
      session[:user_id] = cookies.signed[:user] = @session.user_id
      redirect_to current_user
    else
      render :new
    end
  end

  def destroy
    reset_session
    cookies.delete(:user)
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user

  def show
    @profile_decorator = ProfileDecorator.new(current_user.profile)
    @notifications_count = current_user.received_notifications.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
  def info_if_defined(info)
    info || 'Was not defined'
  end

  def user_avatar(image_url)
    image_tag(image_url)
  end
end

app/views/admin/users/_user_info.slim
tr
  td
    = user.email
  td
    = user.full_name
  td
    = user.location
  td
    = link_to 'Detail', admin_user_path(user)

app/views/admin/users/index.slim
h1 Admin#Users#Index

- if @users.presence
  table
    thead
      tr
        th Email
        th Full Name
        th Location
        th
    tbody
      = render partial: 'user_info', collection: @users, as: :user

app/views/admin/users/show.slim
h1 User's details

table
  tr
    td Email
    td = @user.email
  tr
    td Full Name
    td = @user.full_name
  tr
    td Location
    td = @user.location
  tr
    td Notification
    td
      = simple_form_for @notification, remote: true do |f|
        = f.input :content, label: false
        = f.input :sender_id, as: :hidden, input_html: { value: current_admin.id }
        = f.input :receiver_id, as: :hidden, input_html: { value: @user.id }
        = f.submit :notify

app/views/layouts/_admin_header.slim
' You loged in as Admin |
=> link_to 'Users', admin_users_path
' |
= link_to 'LOG OUT', admin_session_path, method: :delete

app/views/layouts/_developer_header.slim
' You loged in as Developer |
| Notifications (
span#notification_number
  = @notifications_count
' ) |
= link_to 'LOG OUT', session_path, method: :delete

app/views/layouts/_header.slim
| Please login first

app/views/layouts/_logged_header.slim
' You loged in as
=> current_user.type
= link_to 'LOG OUT', session_path, method: :delete

app/views/layouts/admin.slim
doctype html
html
  head
    title Imf
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if current_admin
      = render 'layouts/admin_header'
    br
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Imf
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCfnyFqXCBHa9ZZ31f743160-ahXQSsIuQ" type="text/javascript"
    script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"
    = csrf_meta_tags
    = action_cable_meta_tag

  body
    - if current_user
      = render 'layouts/developer_header'
    - else
      = render 'layouts/header'
    br
    = yield

app/views/profiles/_location.slim
.location id="#{location.place_id}" data-cordinates-lat="#{location.lat}" data-cordinates-lng="#{location.lng}"
  = location.formatted_address

app/views/profiles/edit.slim
h1 Edit Profile
div
  = link_to 'Back', current_user
= simple_form_for @profile, url: user_profile_path(current_user) do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :location, input_html: { id: 'user_location_input' }
  #locations
  #map.map
  = f.submit :update

app/views/users/show.slim
= current_user.email
div
  = user_avatar(@profile_decorator.avatar_thumb)
  = form_tag avatar_user_profile_path(current_user), method: :patch, multipart: true do
    = flash[:avatar]
    = file_field_tag :avatar
    = submit_tag :submit
div
  ' First Name:
  = info_if_defined(@profile_decorator.first_name)
div
  ' Last Name:
  = info_if_defined(@profile_decorator.last_name)
div
  ' Location:
  = info_if_defined(@profile_decorator.location)
div
  = link_to 'Edit Profile', edit_user_profile_path(current_user)
hr
h1 SKILLS
= text_field_tag :skill
hr
h1 JOBS
= link_to 'Add job', '#'
hr
h1 Companies
= link_to 'Add company', '#'